/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCorporationsCorporationIdStructuresCurrentVul', 'model/GetCorporationsCorporationIdStructuresNextVul', 'model/GetCorporationsCorporationIdStructuresService'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetCorporationsCorporationIdStructuresCurrentVul'), require('./GetCorporationsCorporationIdStructuresNextVul'), require('./GetCorporationsCorporationIdStructuresService'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCorporationsCorporationIdStructures200Ok = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetCorporationsCorporationIdStructuresCurrentVul, root.EveSwaggerInterface.GetCorporationsCorporationIdStructuresNextVul, root.EveSwaggerInterface.GetCorporationsCorporationIdStructuresService);
  }
}(this, function(ApiClient, GetCorporationsCorporationIdStructuresCurrentVul, GetCorporationsCorporationIdStructuresNextVul, GetCorporationsCorporationIdStructuresService) {
  'use strict';




  /**
   * The GetCorporationsCorporationIdStructures200Ok model module.
   * @module model/GetCorporationsCorporationIdStructures200Ok
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetCorporationsCorporationIdStructures200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCorporationsCorporationIdStructures200Ok
   * @class
   * @param corporationId {Number} ID of the corporation that owns the structure
   * @param currentVul {Array.<module:model/GetCorporationsCorporationIdStructuresCurrentVul>} This week's vulnerability windows, Monday is day 0
   * @param nextVul {Array.<module:model/GetCorporationsCorporationIdStructuresNextVul>} Next week's vulnerability windows, Monday is day 0
   * @param profileId {Number} The id of the ACL profile for this citadel
   * @param structureId {Number} The Item ID of the structure
   * @param systemId {Number} The solar system the structure is in
   * @param typeId {Number} The type id of the structure
   */
  var exports = function(corporationId, currentVul, nextVul, profileId, structureId, systemId, typeId) {
    var _this = this;

    _this['corporation_id'] = corporationId;
    _this['current_vul'] = currentVul;

    _this['next_vul'] = nextVul;
    _this['profile_id'] = profileId;



    _this['structure_id'] = structureId;
    _this['system_id'] = systemId;
    _this['type_id'] = typeId;

  };

  /**
   * Constructs a <code>GetCorporationsCorporationIdStructures200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCorporationsCorporationIdStructures200Ok} obj Optional instance to populate.
   * @return {module:model/GetCorporationsCorporationIdStructures200Ok} The populated <code>GetCorporationsCorporationIdStructures200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('corporation_id')) {
        obj['corporation_id'] = ApiClient.convertToType(data['corporation_id'], 'Number');
      }
      if (data.hasOwnProperty('current_vul')) {
        obj['current_vul'] = ApiClient.convertToType(data['current_vul'], [GetCorporationsCorporationIdStructuresCurrentVul]);
      }
      if (data.hasOwnProperty('fuel_expires')) {
        obj['fuel_expires'] = ApiClient.convertToType(data['fuel_expires'], 'Date');
      }
      if (data.hasOwnProperty('next_vul')) {
        obj['next_vul'] = ApiClient.convertToType(data['next_vul'], [GetCorporationsCorporationIdStructuresNextVul]);
      }
      if (data.hasOwnProperty('profile_id')) {
        obj['profile_id'] = ApiClient.convertToType(data['profile_id'], 'Number');
      }
      if (data.hasOwnProperty('services')) {
        obj['services'] = ApiClient.convertToType(data['services'], [GetCorporationsCorporationIdStructuresService]);
      }
      if (data.hasOwnProperty('state_timer_end')) {
        obj['state_timer_end'] = ApiClient.convertToType(data['state_timer_end'], 'Date');
      }
      if (data.hasOwnProperty('state_timer_start')) {
        obj['state_timer_start'] = ApiClient.convertToType(data['state_timer_start'], 'Date');
      }
      if (data.hasOwnProperty('structure_id')) {
        obj['structure_id'] = ApiClient.convertToType(data['structure_id'], 'Number');
      }
      if (data.hasOwnProperty('system_id')) {
        obj['system_id'] = ApiClient.convertToType(data['system_id'], 'Number');
      }
      if (data.hasOwnProperty('type_id')) {
        obj['type_id'] = ApiClient.convertToType(data['type_id'], 'Number');
      }
      if (data.hasOwnProperty('unanchors_at')) {
        obj['unanchors_at'] = ApiClient.convertToType(data['unanchors_at'], 'Date');
      }
    }
    return obj;
  }

  /**
   * ID of the corporation that owns the structure
   * @member {Number} corporation_id
   */
  exports.prototype['corporation_id'] = undefined;
  /**
   * This week's vulnerability windows, Monday is day 0
   * @member {Array.<module:model/GetCorporationsCorporationIdStructuresCurrentVul>} current_vul
   */
  exports.prototype['current_vul'] = undefined;
  /**
   * Date on which the structure will run out of fuel
   * @member {Date} fuel_expires
   */
  exports.prototype['fuel_expires'] = undefined;
  /**
   * Next week's vulnerability windows, Monday is day 0
   * @member {Array.<module:model/GetCorporationsCorporationIdStructuresNextVul>} next_vul
   */
  exports.prototype['next_vul'] = undefined;
  /**
   * The id of the ACL profile for this citadel
   * @member {Number} profile_id
   */
  exports.prototype['profile_id'] = undefined;
  /**
   * Contains a list of service upgrades, and their state
   * @member {Array.<module:model/GetCorporationsCorporationIdStructuresService>} services
   */
  exports.prototype['services'] = undefined;
  /**
   * Date at which the structure will move to it's next state
   * @member {Date} state_timer_end
   */
  exports.prototype['state_timer_end'] = undefined;
  /**
   * Date at which the structure entered it's current state
   * @member {Date} state_timer_start
   */
  exports.prototype['state_timer_start'] = undefined;
  /**
   * The Item ID of the structure
   * @member {Number} structure_id
   */
  exports.prototype['structure_id'] = undefined;
  /**
   * The solar system the structure is in
   * @member {Number} system_id
   */
  exports.prototype['system_id'] = undefined;
  /**
   * The type id of the structure
   * @member {Number} type_id
   */
  exports.prototype['type_id'] = undefined;
  /**
   * Date at which the structure will unanchor
   * @member {Date} unanchors_at
   */
  exports.prototype['unanchors_at'] = undefined;



  return exports;
}));


