/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCharactersCharacterIdClonesHomeLocation', 'model/GetCharactersCharacterIdClonesJumpClone'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetCharactersCharacterIdClonesHomeLocation'), require('./GetCharactersCharacterIdClonesJumpClone'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCharactersCharacterIdClonesOk = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetCharactersCharacterIdClonesHomeLocation, root.EveSwaggerInterface.GetCharactersCharacterIdClonesJumpClone);
  }
}(this, function(ApiClient, GetCharactersCharacterIdClonesHomeLocation, GetCharactersCharacterIdClonesJumpClone) {
  'use strict';




  /**
   * The GetCharactersCharacterIdClonesOk model module.
   * @module model/GetCharactersCharacterIdClonesOk
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdClonesOk</code>.
   * 200 ok object
   * @alias module:model/GetCharactersCharacterIdClonesOk
   * @class
   * @param jumpClones {Array.<module:model/GetCharactersCharacterIdClonesJumpClone>} jump_clones array
   */
  var exports = function(jumpClones) {
    var _this = this;


    _this['jump_clones'] = jumpClones;

  };

  /**
   * Constructs a <code>GetCharactersCharacterIdClonesOk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdClonesOk} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdClonesOk} The populated <code>GetCharactersCharacterIdClonesOk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('home_location')) {
        obj['home_location'] = GetCharactersCharacterIdClonesHomeLocation.constructFromObject(data['home_location']);
      }
      if (data.hasOwnProperty('jump_clones')) {
        obj['jump_clones'] = ApiClient.convertToType(data['jump_clones'], [GetCharactersCharacterIdClonesJumpClone]);
      }
      if (data.hasOwnProperty('last_jump_date')) {
        obj['last_jump_date'] = ApiClient.convertToType(data['last_jump_date'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/GetCharactersCharacterIdClonesHomeLocation} home_location
   */
  exports.prototype['home_location'] = undefined;
  /**
   * jump_clones array
   * @member {Array.<module:model/GetCharactersCharacterIdClonesJumpClone>} jump_clones
   */
  exports.prototype['jump_clones'] = undefined;
  /**
   * last_jump_date string
   * @member {Date} last_jump_date
   */
  exports.prototype['last_jump_date'] = undefined;



  return exports;
}));


