/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCharactersCharacterIdSkillsSkill = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetCharactersCharacterIdSkillsSkill model module.
   * @module model/GetCharactersCharacterIdSkillsSkill
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdSkillsSkill</code>.
   * skill object
   * @alias module:model/GetCharactersCharacterIdSkillsSkill
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>GetCharactersCharacterIdSkillsSkill</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdSkillsSkill} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdSkillsSkill} The populated <code>GetCharactersCharacterIdSkillsSkill</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('current_skill_level')) {
        obj['current_skill_level'] = ApiClient.convertToType(data['current_skill_level'], 'Number');
      }
      if (data.hasOwnProperty('skill_id')) {
        obj['skill_id'] = ApiClient.convertToType(data['skill_id'], 'Number');
      }
      if (data.hasOwnProperty('skillpoints_in_skill')) {
        obj['skillpoints_in_skill'] = ApiClient.convertToType(data['skillpoints_in_skill'], 'Number');
      }
    }
    return obj;
  }

  /**
   * current_skill_level integer
   * @member {Number} current_skill_level
   */
  exports.prototype['current_skill_level'] = undefined;
  /**
   * skill_id integer
   * @member {Number} skill_id
   */
  exports.prototype['skill_id'] = undefined;
  /**
   * skillpoints_in_skill integer
   * @member {Number} skillpoints_in_skill
   */
  exports.prototype['skillpoints_in_skill'] = undefined;



  return exports;
}));


