/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCorporationsCorporationIdAlliancehistoryAlliance'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetCorporationsCorporationIdAlliancehistoryAlliance'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCorporationsCorporationIdAlliancehistory200Ok = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetCorporationsCorporationIdAlliancehistoryAlliance);
  }
}(this, function(ApiClient, GetCorporationsCorporationIdAlliancehistoryAlliance) {
  'use strict';




  /**
   * The GetCorporationsCorporationIdAlliancehistory200Ok model module.
   * @module model/GetCorporationsCorporationIdAlliancehistory200Ok
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetCorporationsCorporationIdAlliancehistory200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCorporationsCorporationIdAlliancehistory200Ok
   * @class
   * @param recordId {Number} An incrementing ID that can be used to canonically establish order of records in cases where dates may be ambiguous
   * @param startDate {Date} start_date string
   */
  var exports = function(recordId, startDate) {
    var _this = this;


    _this['record_id'] = recordId;
    _this['start_date'] = startDate;
  };

  /**
   * Constructs a <code>GetCorporationsCorporationIdAlliancehistory200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCorporationsCorporationIdAlliancehistory200Ok} obj Optional instance to populate.
   * @return {module:model/GetCorporationsCorporationIdAlliancehistory200Ok} The populated <code>GetCorporationsCorporationIdAlliancehistory200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('alliance')) {
        obj['alliance'] = GetCorporationsCorporationIdAlliancehistoryAlliance.constructFromObject(data['alliance']);
      }
      if (data.hasOwnProperty('record_id')) {
        obj['record_id'] = ApiClient.convertToType(data['record_id'], 'Number');
      }
      if (data.hasOwnProperty('start_date')) {
        obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/GetCorporationsCorporationIdAlliancehistoryAlliance} alliance
   */
  exports.prototype['alliance'] = undefined;
  /**
   * An incrementing ID that can be used to canonically establish order of records in cases where dates may be ambiguous
   * @member {Number} record_id
   */
  exports.prototype['record_id'] = undefined;
  /**
   * start_date string
   * @member {Date} start_date
   */
  exports.prototype['start_date'] = undefined;



  return exports;
}));


