/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCharactersCharacterIdBookmarksTarget'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetCharactersCharacterIdBookmarksTarget'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCharactersCharacterIdBookmarks200Ok = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetCharactersCharacterIdBookmarksTarget);
  }
}(this, function(ApiClient, GetCharactersCharacterIdBookmarksTarget) {
  'use strict';




  /**
   * The GetCharactersCharacterIdBookmarks200Ok model module.
   * @module model/GetCharactersCharacterIdBookmarks200Ok
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdBookmarks200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCharactersCharacterIdBookmarks200Ok
   * @class
   * @param bookmarkId {Number} bookmark_id integer
   * @param createDate {Date} create_date string
   * @param creatorId {Number} creator_id integer
   * @param memo {String} memo string
   * @param note {String} note string
   * @param ownerId {Number} owner_id integer
   */
  var exports = function(bookmarkId, createDate, creatorId, memo, note, ownerId) {
    var _this = this;

    _this['bookmark_id'] = bookmarkId;
    _this['create_date'] = createDate;
    _this['creator_id'] = creatorId;

    _this['memo'] = memo;
    _this['note'] = note;
    _this['owner_id'] = ownerId;

  };

  /**
   * Constructs a <code>GetCharactersCharacterIdBookmarks200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdBookmarks200Ok} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdBookmarks200Ok} The populated <code>GetCharactersCharacterIdBookmarks200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('bookmark_id')) {
        obj['bookmark_id'] = ApiClient.convertToType(data['bookmark_id'], 'Number');
      }
      if (data.hasOwnProperty('create_date')) {
        obj['create_date'] = ApiClient.convertToType(data['create_date'], 'Date');
      }
      if (data.hasOwnProperty('creator_id')) {
        obj['creator_id'] = ApiClient.convertToType(data['creator_id'], 'Number');
      }
      if (data.hasOwnProperty('folder_id')) {
        obj['folder_id'] = ApiClient.convertToType(data['folder_id'], 'Number');
      }
      if (data.hasOwnProperty('memo')) {
        obj['memo'] = ApiClient.convertToType(data['memo'], 'String');
      }
      if (data.hasOwnProperty('note')) {
        obj['note'] = ApiClient.convertToType(data['note'], 'String');
      }
      if (data.hasOwnProperty('owner_id')) {
        obj['owner_id'] = ApiClient.convertToType(data['owner_id'], 'Number');
      }
      if (data.hasOwnProperty('target')) {
        obj['target'] = GetCharactersCharacterIdBookmarksTarget.constructFromObject(data['target']);
      }
    }
    return obj;
  }

  /**
   * bookmark_id integer
   * @member {Number} bookmark_id
   */
  exports.prototype['bookmark_id'] = undefined;
  /**
   * create_date string
   * @member {Date} create_date
   */
  exports.prototype['create_date'] = undefined;
  /**
   * creator_id integer
   * @member {Number} creator_id
   */
  exports.prototype['creator_id'] = undefined;
  /**
   * folder_id integer
   * @member {Number} folder_id
   */
  exports.prototype['folder_id'] = undefined;
  /**
   * memo string
   * @member {String} memo
   */
  exports.prototype['memo'] = undefined;
  /**
   * note string
   * @member {String} note
   */
  exports.prototype['note'] = undefined;
  /**
   * owner_id integer
   * @member {Number} owner_id
   */
  exports.prototype['owner_id'] = undefined;
  /**
   * @member {module:model/GetCharactersCharacterIdBookmarksTarget} target
   */
  exports.prototype['target'] = undefined;



  return exports;
}));


