/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCharactersCharacterIdBookmarksCoordinates', 'model/GetCharactersCharacterIdBookmarksItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetCharactersCharacterIdBookmarksCoordinates'), require('./GetCharactersCharacterIdBookmarksItem'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCharactersCharacterIdBookmarksTarget = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetCharactersCharacterIdBookmarksCoordinates, root.EveSwaggerInterface.GetCharactersCharacterIdBookmarksItem);
  }
}(this, function(ApiClient, GetCharactersCharacterIdBookmarksCoordinates, GetCharactersCharacterIdBookmarksItem) {
  'use strict';




  /**
   * The GetCharactersCharacterIdBookmarksTarget model module.
   * @module model/GetCharactersCharacterIdBookmarksTarget
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdBookmarksTarget</code>.
   * target object
   * @alias module:model/GetCharactersCharacterIdBookmarksTarget
   * @class
   * @param locationId {Number} location_id integer
   */
  var exports = function(locationId) {
    var _this = this;



    _this['location_id'] = locationId;
  };

  /**
   * Constructs a <code>GetCharactersCharacterIdBookmarksTarget</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdBookmarksTarget} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdBookmarksTarget} The populated <code>GetCharactersCharacterIdBookmarksTarget</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('coordinates')) {
        obj['coordinates'] = GetCharactersCharacterIdBookmarksCoordinates.constructFromObject(data['coordinates']);
      }
      if (data.hasOwnProperty('item')) {
        obj['item'] = GetCharactersCharacterIdBookmarksItem.constructFromObject(data['item']);
      }
      if (data.hasOwnProperty('location_id')) {
        obj['location_id'] = ApiClient.convertToType(data['location_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/GetCharactersCharacterIdBookmarksCoordinates} coordinates
   */
  exports.prototype['coordinates'] = undefined;
  /**
   * @member {module:model/GetCharactersCharacterIdBookmarksItem} item
   */
  exports.prototype['item'] = undefined;
  /**
   * location_id integer
   * @member {Number} location_id
   */
  exports.prototype['location_id'] = undefined;



  return exports;
}));


