/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCharactersCharacterIdWallets200Ok = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetCharactersCharacterIdWallets200Ok model module.
   * @module model/GetCharactersCharacterIdWallets200Ok
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdWallets200Ok</code>.
   * 200 ok object
   * @alias module:model/GetCharactersCharacterIdWallets200Ok
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>GetCharactersCharacterIdWallets200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdWallets200Ok} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdWallets200Ok} The populated <code>GetCharactersCharacterIdWallets200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('balance')) {
        obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
      }
      if (data.hasOwnProperty('wallet_id')) {
        obj['wallet_id'] = ApiClient.convertToType(data['wallet_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Wallet's balance in ISK hundredths.
   * @member {Number} balance
   */
  exports.prototype['balance'] = undefined;
  /**
   * wallet_id integer
   * @member {Number} wallet_id
   */
  exports.prototype['wallet_id'] = undefined;



  return exports;
}));


