/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCharactersCharacterIdSkillsSkill'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetCharactersCharacterIdSkillsSkill'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCharactersCharacterIdSkillsOk = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetCharactersCharacterIdSkillsSkill);
  }
}(this, function(ApiClient, GetCharactersCharacterIdSkillsSkill) {
  'use strict';




  /**
   * The GetCharactersCharacterIdSkillsOk model module.
   * @module model/GetCharactersCharacterIdSkillsOk
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdSkillsOk</code>.
   * 200 ok object
   * @alias module:model/GetCharactersCharacterIdSkillsOk
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>GetCharactersCharacterIdSkillsOk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdSkillsOk} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdSkillsOk} The populated <code>GetCharactersCharacterIdSkillsOk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('skills')) {
        obj['skills'] = ApiClient.convertToType(data['skills'], [GetCharactersCharacterIdSkillsSkill]);
      }
      if (data.hasOwnProperty('total_sp')) {
        obj['total_sp'] = ApiClient.convertToType(data['total_sp'], 'Number');
      }
    }
    return obj;
  }

  /**
   * skills array
   * @member {Array.<module:model/GetCharactersCharacterIdSkillsSkill>} skills
   */
  exports.prototype['skills'] = undefined;
  /**
   * total_sp integer
   * @member {Number} total_sp
   */
  exports.prototype['total_sp'] = undefined;



  return exports;
}));


