/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetCharactersCharacterIdPlanetsPlanetIdWaypoint = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetCharactersCharacterIdPlanetsPlanetIdWaypoint model module.
   * @module model/GetCharactersCharacterIdPlanetsPlanetIdWaypoint
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetCharactersCharacterIdPlanetsPlanetIdWaypoint</code>.
   * waypoint object
   * @alias module:model/GetCharactersCharacterIdPlanetsPlanetIdWaypoint
   * @class
   * @param order {Number} order integer
   * @param pinId {Number} pin_id integer
   */
  var exports = function(order, pinId) {
    var _this = this;

    _this['order'] = order;
    _this['pin_id'] = pinId;
  };

  /**
   * Constructs a <code>GetCharactersCharacterIdPlanetsPlanetIdWaypoint</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetCharactersCharacterIdPlanetsPlanetIdWaypoint} obj Optional instance to populate.
   * @return {module:model/GetCharactersCharacterIdPlanetsPlanetIdWaypoint} The populated <code>GetCharactersCharacterIdPlanetsPlanetIdWaypoint</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('order')) {
        obj['order'] = ApiClient.convertToType(data['order'], 'Number');
      }
      if (data.hasOwnProperty('pin_id')) {
        obj['pin_id'] = ApiClient.convertToType(data['pin_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * order integer
   * @member {Number} order
   */
  exports.prototype['order'] = undefined;
  /**
   * pin_id integer
   * @member {Number} pin_id
   */
  exports.prototype['pin_id'] = undefined;



  return exports;
}));


