/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetDogmaEffectsEffectIdModifier = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetDogmaEffectsEffectIdModifier model module.
   * @module model/GetDogmaEffectsEffectIdModifier
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetDogmaEffectsEffectIdModifier</code>.
   * modifier object
   * @alias module:model/GetDogmaEffectsEffectIdModifier
   * @class
   * @param domain {String} domain string
   * @param func {String} func string
   * @param modifiedAttributeId {Number} modified_attribute_id integer
   * @param modifyingAttributeId {Number} modifying_attribute_id integer
   * @param operator {Number} operator integer
   */
  var exports = function(domain, func, modifiedAttributeId, modifyingAttributeId, operator) {
    var _this = this;

    _this['domain'] = domain;
    _this['func'] = func;
    _this['modified_attribute_id'] = modifiedAttributeId;
    _this['modifying_attribute_id'] = modifyingAttributeId;
    _this['operator'] = operator;
  };

  /**
   * Constructs a <code>GetDogmaEffectsEffectIdModifier</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetDogmaEffectsEffectIdModifier} obj Optional instance to populate.
   * @return {module:model/GetDogmaEffectsEffectIdModifier} The populated <code>GetDogmaEffectsEffectIdModifier</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('domain')) {
        obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
      }
      if (data.hasOwnProperty('func')) {
        obj['func'] = ApiClient.convertToType(data['func'], 'String');
      }
      if (data.hasOwnProperty('modified_attribute_id')) {
        obj['modified_attribute_id'] = ApiClient.convertToType(data['modified_attribute_id'], 'Number');
      }
      if (data.hasOwnProperty('modifying_attribute_id')) {
        obj['modifying_attribute_id'] = ApiClient.convertToType(data['modifying_attribute_id'], 'Number');
      }
      if (data.hasOwnProperty('operator')) {
        obj['operator'] = ApiClient.convertToType(data['operator'], 'Number');
      }
    }
    return obj;
  }

  /**
   * domain string
   * @member {String} domain
   */
  exports.prototype['domain'] = undefined;
  /**
   * func string
   * @member {String} func
   */
  exports.prototype['func'] = undefined;
  /**
   * modified_attribute_id integer
   * @member {Number} modified_attribute_id
   */
  exports.prototype['modified_attribute_id'] = undefined;
  /**
   * modifying_attribute_id integer
   * @member {Number} modifying_attribute_id
   */
  exports.prototype['modifying_attribute_id'] = undefined;
  /**
   * operator integer
   * @member {Number} operator
   */
  exports.prototype['operator'] = undefined;



  return exports;
}));


