/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetKillmailsKillmailIdKillmailHashItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetKillmailsKillmailIdKillmailHashItem'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem1 = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashItem);
  }
}(this, function(ApiClient, GetKillmailsKillmailIdKillmailHashItem) {
  'use strict';




  /**
   * The GetKillmailsKillmailIdKillmailHashItem1 model module.
   * @module model/GetKillmailsKillmailIdKillmailHashItem1
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetKillmailsKillmailIdKillmailHashItem1</code>.
   * item object
   * @alias module:model/GetKillmailsKillmailIdKillmailHashItem1
   * @class
   * @param flag {Number} Flag for the location of the item 
   * @param itemTypeId {Number} item_type_id integer
   * @param singleton {Number} singleton integer
   */
  var exports = function(flag, itemTypeId, singleton) {
    var _this = this;

    _this['flag'] = flag;
    _this['item_type_id'] = itemTypeId;



    _this['singleton'] = singleton;
  };

  /**
   * Constructs a <code>GetKillmailsKillmailIdKillmailHashItem1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetKillmailsKillmailIdKillmailHashItem1} obj Optional instance to populate.
   * @return {module:model/GetKillmailsKillmailIdKillmailHashItem1} The populated <code>GetKillmailsKillmailIdKillmailHashItem1</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('flag')) {
        obj['flag'] = ApiClient.convertToType(data['flag'], 'Number');
      }
      if (data.hasOwnProperty('item_type_id')) {
        obj['item_type_id'] = ApiClient.convertToType(data['item_type_id'], 'Number');
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [GetKillmailsKillmailIdKillmailHashItem]);
      }
      if (data.hasOwnProperty('quantity_destroyed')) {
        obj['quantity_destroyed'] = ApiClient.convertToType(data['quantity_destroyed'], 'Number');
      }
      if (data.hasOwnProperty('quantity_dropped')) {
        obj['quantity_dropped'] = ApiClient.convertToType(data['quantity_dropped'], 'Number');
      }
      if (data.hasOwnProperty('singleton')) {
        obj['singleton'] = ApiClient.convertToType(data['singleton'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Flag for the location of the item 
   * @member {Number} flag
   */
  exports.prototype['flag'] = undefined;
  /**
   * item_type_id integer
   * @member {Number} item_type_id
   */
  exports.prototype['item_type_id'] = undefined;
  /**
   * items array
   * @member {Array.<module:model/GetKillmailsKillmailIdKillmailHashItem>} items
   */
  exports.prototype['items'] = undefined;
  /**
   * How many of the item were destroyed if any 
   * @member {Number} quantity_destroyed
   */
  exports.prototype['quantity_destroyed'] = undefined;
  /**
   * How many of the item were dropped if any 
   * @member {Number} quantity_dropped
   */
  exports.prototype['quantity_dropped'] = undefined;
  /**
   * singleton integer
   * @member {Number} singleton
   */
  exports.prototype['singleton'] = undefined;



  return exports;
}));


