/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetKillmailsKillmailIdKillmailHashAttacker', 'model/GetKillmailsKillmailIdKillmailHashVictim'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetKillmailsKillmailIdKillmailHashAttacker'), require('./GetKillmailsKillmailIdKillmailHashVictim'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashOk = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashAttacker, root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashVictim);
  }
}(this, function(ApiClient, GetKillmailsKillmailIdKillmailHashAttacker, GetKillmailsKillmailIdKillmailHashVictim) {
  'use strict';




  /**
   * The GetKillmailsKillmailIdKillmailHashOk model module.
   * @module model/GetKillmailsKillmailIdKillmailHashOk
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetKillmailsKillmailIdKillmailHashOk</code>.
   * 200 ok object
   * @alias module:model/GetKillmailsKillmailIdKillmailHashOk
   * @class
   * @param attackers {Array.<module:model/GetKillmailsKillmailIdKillmailHashAttacker>} attackers array
   * @param killmailId {Number} ID of the killmail
   * @param killmailTime {Date} Time that the victim was killed and the killmail generated 
   * @param solarSystemId {Number} Solar system that the kill took place in 
   */
  var exports = function(attackers, killmailId, killmailTime, solarSystemId) {
    var _this = this;

    _this['attackers'] = attackers;
    _this['killmail_id'] = killmailId;
    _this['killmail_time'] = killmailTime;

    _this['solar_system_id'] = solarSystemId;


  };

  /**
   * Constructs a <code>GetKillmailsKillmailIdKillmailHashOk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetKillmailsKillmailIdKillmailHashOk} obj Optional instance to populate.
   * @return {module:model/GetKillmailsKillmailIdKillmailHashOk} The populated <code>GetKillmailsKillmailIdKillmailHashOk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('attackers')) {
        obj['attackers'] = ApiClient.convertToType(data['attackers'], [GetKillmailsKillmailIdKillmailHashAttacker]);
      }
      if (data.hasOwnProperty('killmail_id')) {
        obj['killmail_id'] = ApiClient.convertToType(data['killmail_id'], 'Number');
      }
      if (data.hasOwnProperty('killmail_time')) {
        obj['killmail_time'] = ApiClient.convertToType(data['killmail_time'], 'Date');
      }
      if (data.hasOwnProperty('moon_id')) {
        obj['moon_id'] = ApiClient.convertToType(data['moon_id'], 'Number');
      }
      if (data.hasOwnProperty('solar_system_id')) {
        obj['solar_system_id'] = ApiClient.convertToType(data['solar_system_id'], 'Number');
      }
      if (data.hasOwnProperty('victim')) {
        obj['victim'] = GetKillmailsKillmailIdKillmailHashVictim.constructFromObject(data['victim']);
      }
      if (data.hasOwnProperty('war_id')) {
        obj['war_id'] = ApiClient.convertToType(data['war_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * attackers array
   * @member {Array.<module:model/GetKillmailsKillmailIdKillmailHashAttacker>} attackers
   */
  exports.prototype['attackers'] = undefined;
  /**
   * ID of the killmail
   * @member {Number} killmail_id
   */
  exports.prototype['killmail_id'] = undefined;
  /**
   * Time that the victim was killed and the killmail generated 
   * @member {Date} killmail_time
   */
  exports.prototype['killmail_time'] = undefined;
  /**
   * Moon if the kill took place at one
   * @member {Number} moon_id
   */
  exports.prototype['moon_id'] = undefined;
  /**
   * Solar system that the kill took place in 
   * @member {Number} solar_system_id
   */
  exports.prototype['solar_system_id'] = undefined;
  /**
   * @member {module:model/GetKillmailsKillmailIdKillmailHashVictim} victim
   */
  exports.prototype['victim'] = undefined;
  /**
   * War if the killmail is generated in relation to an official war 
   * @member {Number} war_id
   */
  exports.prototype['war_id'] = undefined;



  return exports;
}));


