/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetSearchOk = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetSearchOk model module.
   * @module model/GetSearchOk
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetSearchOk</code>.
   * 200 ok object
   * @alias module:model/GetSearchOk
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>GetSearchOk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetSearchOk} obj Optional instance to populate.
   * @return {module:model/GetSearchOk} The populated <code>GetSearchOk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('agent')) {
        obj['agent'] = ApiClient.convertToType(data['agent'], ['Number']);
      }
      if (data.hasOwnProperty('alliance')) {
        obj['alliance'] = ApiClient.convertToType(data['alliance'], ['Number']);
      }
      if (data.hasOwnProperty('character')) {
        obj['character'] = ApiClient.convertToType(data['character'], ['Number']);
      }
      if (data.hasOwnProperty('constellation')) {
        obj['constellation'] = ApiClient.convertToType(data['constellation'], ['Number']);
      }
      if (data.hasOwnProperty('corporation')) {
        obj['corporation'] = ApiClient.convertToType(data['corporation'], ['Number']);
      }
      if (data.hasOwnProperty('faction')) {
        obj['faction'] = ApiClient.convertToType(data['faction'], ['Number']);
      }
      if (data.hasOwnProperty('inventorytype')) {
        obj['inventorytype'] = ApiClient.convertToType(data['inventorytype'], ['Number']);
      }
      if (data.hasOwnProperty('region')) {
        obj['region'] = ApiClient.convertToType(data['region'], ['Number']);
      }
      if (data.hasOwnProperty('solarsystem')) {
        obj['solarsystem'] = ApiClient.convertToType(data['solarsystem'], ['Number']);
      }
      if (data.hasOwnProperty('station')) {
        obj['station'] = ApiClient.convertToType(data['station'], ['Number']);
      }
      if (data.hasOwnProperty('wormhole')) {
        obj['wormhole'] = ApiClient.convertToType(data['wormhole'], ['Number']);
      }
    }
    return obj;
  }

  /**
   * agent array
   * @member {Array.<Number>} agent
   */
  exports.prototype['agent'] = undefined;
  /**
   * alliance array
   * @member {Array.<Number>} alliance
   */
  exports.prototype['alliance'] = undefined;
  /**
   * character array
   * @member {Array.<Number>} character
   */
  exports.prototype['character'] = undefined;
  /**
   * constellation array
   * @member {Array.<Number>} constellation
   */
  exports.prototype['constellation'] = undefined;
  /**
   * corporation array
   * @member {Array.<Number>} corporation
   */
  exports.prototype['corporation'] = undefined;
  /**
   * faction array
   * @member {Array.<Number>} faction
   */
  exports.prototype['faction'] = undefined;
  /**
   * inventorytype array
   * @member {Array.<Number>} inventorytype
   */
  exports.prototype['inventorytype'] = undefined;
  /**
   * region array
   * @member {Array.<Number>} region
   */
  exports.prototype['region'] = undefined;
  /**
   * solarsystem array
   * @member {Array.<Number>} solarsystem
   */
  exports.prototype['solarsystem'] = undefined;
  /**
   * station array
   * @member {Array.<Number>} station
   */
  exports.prototype['station'] = undefined;
  /**
   * wormhole array
   * @member {Array.<Number>} wormhole
   */
  exports.prototype['wormhole'] = undefined;



  return exports;
}));


