/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetUniverseRaces200Ok = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetUniverseRaces200Ok model module.
   * @module model/GetUniverseRaces200Ok
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetUniverseRaces200Ok</code>.
   * 200 ok object
   * @alias module:model/GetUniverseRaces200Ok
   * @class
   * @param allianceId {Number} The alliance generally associated with this race
   * @param description {String} description string
   * @param name {String} name string
   * @param raceId {Number} race_id integer
   */
  var exports = function(allianceId, description, name, raceId) {
    var _this = this;

    _this['alliance_id'] = allianceId;
    _this['description'] = description;
    _this['name'] = name;
    _this['race_id'] = raceId;
  };

  /**
   * Constructs a <code>GetUniverseRaces200Ok</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetUniverseRaces200Ok} obj Optional instance to populate.
   * @return {module:model/GetUniverseRaces200Ok} The populated <code>GetUniverseRaces200Ok</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('alliance_id')) {
        obj['alliance_id'] = ApiClient.convertToType(data['alliance_id'], 'Number');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('race_id')) {
        obj['race_id'] = ApiClient.convertToType(data['race_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The alliance generally associated with this race
   * @member {Number} alliance_id
   */
  exports.prototype['alliance_id'] = undefined;
  /**
   * description string
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * name string
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * race_id integer
   * @member {Number} race_id
   */
  exports.prototype['race_id'] = undefined;



  return exports;
}));


