/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.GetUniverseGraphicsGraphicIdOk = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GetUniverseGraphicsGraphicIdOk model module.
   * @module model/GetUniverseGraphicsGraphicIdOk
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>GetUniverseGraphicsGraphicIdOk</code>.
   * 200 ok object
   * @alias module:model/GetUniverseGraphicsGraphicIdOk
   * @class
   * @param graphicId {Number} graphic_id integer
   */
  var exports = function(graphicId) {
    var _this = this;



    _this['graphic_id'] = graphicId;





  };

  /**
   * Constructs a <code>GetUniverseGraphicsGraphicIdOk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetUniverseGraphicsGraphicIdOk} obj Optional instance to populate.
   * @return {module:model/GetUniverseGraphicsGraphicIdOk} The populated <code>GetUniverseGraphicsGraphicIdOk</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('collision_file')) {
        obj['collision_file'] = ApiClient.convertToType(data['collision_file'], 'String');
      }
      if (data.hasOwnProperty('graphic_file')) {
        obj['graphic_file'] = ApiClient.convertToType(data['graphic_file'], 'String');
      }
      if (data.hasOwnProperty('graphic_id')) {
        obj['graphic_id'] = ApiClient.convertToType(data['graphic_id'], 'Number');
      }
      if (data.hasOwnProperty('icon_folder')) {
        obj['icon_folder'] = ApiClient.convertToType(data['icon_folder'], 'String');
      }
      if (data.hasOwnProperty('sof_dna')) {
        obj['sof_dna'] = ApiClient.convertToType(data['sof_dna'], 'String');
      }
      if (data.hasOwnProperty('sof_fation_name')) {
        obj['sof_fation_name'] = ApiClient.convertToType(data['sof_fation_name'], 'String');
      }
      if (data.hasOwnProperty('sof_hull_name')) {
        obj['sof_hull_name'] = ApiClient.convertToType(data['sof_hull_name'], 'String');
      }
      if (data.hasOwnProperty('sof_race_name')) {
        obj['sof_race_name'] = ApiClient.convertToType(data['sof_race_name'], 'String');
      }
    }
    return obj;
  }

  /**
   * collision_file string
   * @member {String} collision_file
   */
  exports.prototype['collision_file'] = undefined;
  /**
   * graphic_file string
   * @member {String} graphic_file
   */
  exports.prototype['graphic_file'] = undefined;
  /**
   * graphic_id integer
   * @member {Number} graphic_id
   */
  exports.prototype['graphic_id'] = undefined;
  /**
   * icon_folder string
   * @member {String} icon_folder
   */
  exports.prototype['icon_folder'] = undefined;
  /**
   * sof_dna string
   * @member {String} sof_dna
   */
  exports.prototype['sof_dna'] = undefined;
  /**
   * sof_fation_name string
   * @member {String} sof_fation_name
   */
  exports.prototype['sof_fation_name'] = undefined;
  /**
   * sof_hull_name string
   * @member {String} sof_hull_name
   */
  exports.prototype['sof_hull_name'] = undefined;
  /**
   * sof_race_name string
   * @member {String} sof_race_name
   */
  exports.prototype['sof_race_name'] = undefined;



  return exports;
}));


