/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.PostCharactersCharacterIdCspaCharacters = factory(root.EveSwaggerInterface.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PostCharactersCharacterIdCspaCharacters model module.
   * @module model/PostCharactersCharacterIdCspaCharacters
   * @version 0.4.1
   */

  /**
   * Constructs a new <code>PostCharactersCharacterIdCspaCharacters</code>.
   * characters schema
   * @alias module:model/PostCharactersCharacterIdCspaCharacters
   * @class
   * @param characters {Array.<Number>} characters array
   */
  var exports = function(characters) {
    var _this = this;

    _this['characters'] = characters;
  };

  /**
   * Constructs a <code>PostCharactersCharacterIdCspaCharacters</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PostCharactersCharacterIdCspaCharacters} obj Optional instance to populate.
   * @return {module:model/PostCharactersCharacterIdCspaCharacters} The populated <code>PostCharactersCharacterIdCspaCharacters</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('characters')) {
        obj['characters'] = ApiClient.convertToType(data['characters'], ['Number']);
      }
    }
    return obj;
  }

  /**
   * characters array
   * @member {Array.<Number>} characters
   */
  exports.prototype['characters'] = undefined;



  return exports;
}));


