/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCharactersCharacterIdKillmailsRecent200Ok', 'model/GetCharactersCharacterIdKillmailsRecentForbidden', 'model/GetCharactersCharacterIdKillmailsRecentInternalServerError', 'model/GetKillmailsKillmailIdKillmailHashInternalServerError', 'model/GetKillmailsKillmailIdKillmailHashOk', 'model/GetKillmailsKillmailIdKillmailHashUnprocessableEntity'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GetCharactersCharacterIdKillmailsRecent200Ok'), require('../model/GetCharactersCharacterIdKillmailsRecentForbidden'), require('../model/GetCharactersCharacterIdKillmailsRecentInternalServerError'), require('../model/GetKillmailsKillmailIdKillmailHashInternalServerError'), require('../model/GetKillmailsKillmailIdKillmailHashOk'), require('../model/GetKillmailsKillmailIdKillmailHashUnprocessableEntity'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.KillmailsApi = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetCharactersCharacterIdKillmailsRecent200Ok, root.EveSwaggerInterface.GetCharactersCharacterIdKillmailsRecentForbidden, root.EveSwaggerInterface.GetCharactersCharacterIdKillmailsRecentInternalServerError, root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashInternalServerError, root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashOk, root.EveSwaggerInterface.GetKillmailsKillmailIdKillmailHashUnprocessableEntity);
  }
}(this, function(ApiClient, GetCharactersCharacterIdKillmailsRecent200Ok, GetCharactersCharacterIdKillmailsRecentForbidden, GetCharactersCharacterIdKillmailsRecentInternalServerError, GetKillmailsKillmailIdKillmailHashInternalServerError, GetKillmailsKillmailIdKillmailHashOk, GetKillmailsKillmailIdKillmailHashUnprocessableEntity) {
  'use strict';

  /**
   * Killmails service.
   * @module api/KillmailsApi
   * @version 0.4.1
   */

  /**
   * Constructs a new KillmailsApi. 
   * @alias module:api/KillmailsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getCharactersCharacterIdKillmailsRecent operation.
     * @callback module:api/KillmailsApi~getCharactersCharacterIdKillmailsRecentCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/GetCharactersCharacterIdKillmailsRecent200Ok>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List kills and losses
     * Return a list of character&#39;s recent kills and losses  ---  Alternate route: &#x60;/v1/characters/{character_id}/killmails/recent/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/killmails/recent/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/killmails/recent/&#x60;   ---  This route is cached for up to 120 seconds
     * @param {Number} characterId An EVE character ID
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.datasource The server name you would like data from (default to tranquility)
     * @param {Number} opts.maxCount How many killmails to return at maximum (default to 50)
     * @param {Number} opts.maxKillId Only return killmails with ID smaller than this. 
     * @param {String} opts.token Access token to use, if preferred over a header
     * @param {String} opts.userAgent Client identifier, takes precedence over headers
     * @param {String} opts.xUserAgent Client identifier, takes precedence over User-Agent
     * @param {module:api/KillmailsApi~getCharactersCharacterIdKillmailsRecentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/GetCharactersCharacterIdKillmailsRecent200Ok>}
     */
    this.getCharactersCharacterIdKillmailsRecent = function(characterId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'characterId' is set
      if (characterId == undefined || characterId == null) {
        throw new Error("Missing the required parameter 'characterId' when calling getCharactersCharacterIdKillmailsRecent");
      }


      var pathParams = {
        'character_id': characterId
      };
      var queryParams = {
        'datasource': opts['datasource'],
        'max_count': opts['maxCount'],
        'max_kill_id': opts['maxKillId'],
        'token': opts['token'],
        'user_agent': opts['userAgent']
      };
      var headerParams = {
        'X-User-Agent': opts['xUserAgent']
      };
      var formParams = {
      };

      var authNames = ['evesso'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [GetCharactersCharacterIdKillmailsRecent200Ok];

      return this.apiClient.callApi(
        '/characters/{character_id}/killmails/recent/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getKillmailsKillmailIdKillmailHash operation.
     * @callback module:api/KillmailsApi~getKillmailsKillmailIdKillmailHashCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetKillmailsKillmailIdKillmailHashOk} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a single killmail
     * Return a single killmail from its ID and hash  ---  Alternate route: &#x60;/v1/killmails/{killmail_id}/{killmail_hash}/&#x60;  Alternate route: &#x60;/legacy/killmails/{killmail_id}/{killmail_hash}/&#x60;  Alternate route: &#x60;/dev/killmails/{killmail_id}/{killmail_hash}/&#x60;   ---  This route is cached for up to 3600 seconds
     * @param {String} killmailHash The killmail hash for verification
     * @param {Number} killmailId The killmail ID to be queried
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.datasource The server name you would like data from (default to tranquility)
     * @param {String} opts.userAgent Client identifier, takes precedence over headers
     * @param {String} opts.xUserAgent Client identifier, takes precedence over User-Agent
     * @param {module:api/KillmailsApi~getKillmailsKillmailIdKillmailHashCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetKillmailsKillmailIdKillmailHashOk}
     */
    this.getKillmailsKillmailIdKillmailHash = function(killmailHash, killmailId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'killmailHash' is set
      if (killmailHash == undefined || killmailHash == null) {
        throw new Error("Missing the required parameter 'killmailHash' when calling getKillmailsKillmailIdKillmailHash");
      }

      // verify the required parameter 'killmailId' is set
      if (killmailId == undefined || killmailId == null) {
        throw new Error("Missing the required parameter 'killmailId' when calling getKillmailsKillmailIdKillmailHash");
      }


      var pathParams = {
        'killmail_hash': killmailHash,
        'killmail_id': killmailId
      };
      var queryParams = {
        'datasource': opts['datasource'],
        'user_agent': opts['userAgent']
      };
      var headerParams = {
        'X-User-Agent': opts['xUserAgent']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = GetKillmailsKillmailIdKillmailHashOk;

      return this.apiClient.callApi(
        '/killmails/{killmail_id}/{killmail_hash}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
