/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetCharactersCharacterIdOpportunities200Ok', 'model/GetCharactersCharacterIdOpportunitiesForbidden', 'model/GetCharactersCharacterIdOpportunitiesInternalServerError', 'model/GetOpportunitiesGroupsGroupIdInternalServerError', 'model/GetOpportunitiesGroupsGroupIdOk', 'model/GetOpportunitiesGroupsInternalServerError', 'model/GetOpportunitiesTasksInternalServerError', 'model/GetOpportunitiesTasksTaskIdInternalServerError', 'model/GetOpportunitiesTasksTaskIdOk'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GetCharactersCharacterIdOpportunities200Ok'), require('../model/GetCharactersCharacterIdOpportunitiesForbidden'), require('../model/GetCharactersCharacterIdOpportunitiesInternalServerError'), require('../model/GetOpportunitiesGroupsGroupIdInternalServerError'), require('../model/GetOpportunitiesGroupsGroupIdOk'), require('../model/GetOpportunitiesGroupsInternalServerError'), require('../model/GetOpportunitiesTasksInternalServerError'), require('../model/GetOpportunitiesTasksTaskIdInternalServerError'), require('../model/GetOpportunitiesTasksTaskIdOk'));
  } else {
    // Browser globals (root is window)
    if (!root.EveSwaggerInterface) {
      root.EveSwaggerInterface = {};
    }
    root.EveSwaggerInterface.OpportunitiesApi = factory(root.EveSwaggerInterface.ApiClient, root.EveSwaggerInterface.GetCharactersCharacterIdOpportunities200Ok, root.EveSwaggerInterface.GetCharactersCharacterIdOpportunitiesForbidden, root.EveSwaggerInterface.GetCharactersCharacterIdOpportunitiesInternalServerError, root.EveSwaggerInterface.GetOpportunitiesGroupsGroupIdInternalServerError, root.EveSwaggerInterface.GetOpportunitiesGroupsGroupIdOk, root.EveSwaggerInterface.GetOpportunitiesGroupsInternalServerError, root.EveSwaggerInterface.GetOpportunitiesTasksInternalServerError, root.EveSwaggerInterface.GetOpportunitiesTasksTaskIdInternalServerError, root.EveSwaggerInterface.GetOpportunitiesTasksTaskIdOk);
  }
}(this, function(ApiClient, GetCharactersCharacterIdOpportunities200Ok, GetCharactersCharacterIdOpportunitiesForbidden, GetCharactersCharacterIdOpportunitiesInternalServerError, GetOpportunitiesGroupsGroupIdInternalServerError, GetOpportunitiesGroupsGroupIdOk, GetOpportunitiesGroupsInternalServerError, GetOpportunitiesTasksInternalServerError, GetOpportunitiesTasksTaskIdInternalServerError, GetOpportunitiesTasksTaskIdOk) {
  'use strict';

  /**
   * Opportunities service.
   * @module api/OpportunitiesApi
   * @version 0.4.1
   */

  /**
   * Constructs a new OpportunitiesApi. 
   * @alias module:api/OpportunitiesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getCharactersCharacterIdOpportunities operation.
     * @callback module:api/OpportunitiesApi~getCharactersCharacterIdOpportunitiesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/GetCharactersCharacterIdOpportunities200Ok>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a character&#39;s completed tasks
     * Return a list of tasks finished by a character  ---  Alternate route: &#x60;/v1/characters/{character_id}/opportunities/&#x60;  Alternate route: &#x60;/legacy/characters/{character_id}/opportunities/&#x60;  Alternate route: &#x60;/dev/characters/{character_id}/opportunities/&#x60;   ---  This route is cached for up to 3600 seconds
     * @param {Number} characterId ID for a character
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.datasource The server name you would like data from (default to tranquility)
     * @param {String} opts.token Access token to use, if preferred over a header
     * @param {String} opts.userAgent Client identifier, takes precedence over headers
     * @param {String} opts.xUserAgent Client identifier, takes precedence over User-Agent
     * @param {module:api/OpportunitiesApi~getCharactersCharacterIdOpportunitiesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/GetCharactersCharacterIdOpportunities200Ok>}
     */
    this.getCharactersCharacterIdOpportunities = function(characterId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'characterId' is set
      if (characterId == undefined || characterId == null) {
        throw new Error("Missing the required parameter 'characterId' when calling getCharactersCharacterIdOpportunities");
      }


      var pathParams = {
        'character_id': characterId
      };
      var queryParams = {
        'datasource': opts['datasource'],
        'token': opts['token'],
        'user_agent': opts['userAgent']
      };
      var headerParams = {
        'X-User-Agent': opts['xUserAgent']
      };
      var formParams = {
      };

      var authNames = ['evesso'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [GetCharactersCharacterIdOpportunities200Ok];

      return this.apiClient.callApi(
        '/characters/{character_id}/opportunities/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getOpportunitiesGroups operation.
     * @callback module:api/OpportunitiesApi~getOpportunitiesGroupsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<'Number'>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get opportunities groups
     * Return a list of opportunities groups  ---  Alternate route: &#x60;/v1/opportunities/groups/&#x60;  Alternate route: &#x60;/legacy/opportunities/groups/&#x60;  Alternate route: &#x60;/dev/opportunities/groups/&#x60;   ---  This route is cached for up to 3600 seconds
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.datasource The server name you would like data from (default to tranquility)
     * @param {String} opts.userAgent Client identifier, takes precedence over headers
     * @param {String} opts.xUserAgent Client identifier, takes precedence over User-Agent
     * @param {module:api/OpportunitiesApi~getOpportunitiesGroupsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<'Number'>}
     */
    this.getOpportunitiesGroups = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'datasource': opts['datasource'],
        'user_agent': opts['userAgent']
      };
      var headerParams = {
        'X-User-Agent': opts['xUserAgent']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ['Number'];

      return this.apiClient.callApi(
        '/opportunities/groups/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getOpportunitiesGroupsGroupId operation.
     * @callback module:api/OpportunitiesApi~getOpportunitiesGroupsGroupIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetOpportunitiesGroupsGroupIdOk} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get opportunities group
     * Return information of an opportunities group  ---  Alternate route: &#x60;/v1/opportunities/groups/{group_id}/&#x60;  Alternate route: &#x60;/legacy/opportunities/groups/{group_id}/&#x60;  Alternate route: &#x60;/dev/opportunities/groups/{group_id}/&#x60;   ---  This route is cached for up to 3600 seconds
     * @param {Number} groupId ID of an opportunities group
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.datasource The server name you would like data from (default to tranquility)
     * @param {module:model/String} opts.language Language to use in the response (default to en-us)
     * @param {String} opts.userAgent Client identifier, takes precedence over headers
     * @param {String} opts.xUserAgent Client identifier, takes precedence over User-Agent
     * @param {module:api/OpportunitiesApi~getOpportunitiesGroupsGroupIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetOpportunitiesGroupsGroupIdOk}
     */
    this.getOpportunitiesGroupsGroupId = function(groupId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'groupId' is set
      if (groupId == undefined || groupId == null) {
        throw new Error("Missing the required parameter 'groupId' when calling getOpportunitiesGroupsGroupId");
      }


      var pathParams = {
        'group_id': groupId
      };
      var queryParams = {
        'datasource': opts['datasource'],
        'language': opts['language'],
        'user_agent': opts['userAgent']
      };
      var headerParams = {
        'X-User-Agent': opts['xUserAgent']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = GetOpportunitiesGroupsGroupIdOk;

      return this.apiClient.callApi(
        '/opportunities/groups/{group_id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getOpportunitiesTasks operation.
     * @callback module:api/OpportunitiesApi~getOpportunitiesTasksCallback
     * @param {String} error Error message, if any.
     * @param {Array.<'Number'>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get opportunities tasks
     * Return a list of opportunities tasks  ---  Alternate route: &#x60;/v1/opportunities/tasks/&#x60;  Alternate route: &#x60;/legacy/opportunities/tasks/&#x60;  Alternate route: &#x60;/dev/opportunities/tasks/&#x60;   ---  This route is cached for up to 3600 seconds
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.datasource The server name you would like data from (default to tranquility)
     * @param {String} opts.userAgent Client identifier, takes precedence over headers
     * @param {String} opts.xUserAgent Client identifier, takes precedence over User-Agent
     * @param {module:api/OpportunitiesApi~getOpportunitiesTasksCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<'Number'>}
     */
    this.getOpportunitiesTasks = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'datasource': opts['datasource'],
        'user_agent': opts['userAgent']
      };
      var headerParams = {
        'X-User-Agent': opts['xUserAgent']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ['Number'];

      return this.apiClient.callApi(
        '/opportunities/tasks/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getOpportunitiesTasksTaskId operation.
     * @callback module:api/OpportunitiesApi~getOpportunitiesTasksTaskIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetOpportunitiesTasksTaskIdOk} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get opportunities task
     * Return information of an opportunities task  ---  Alternate route: &#x60;/v1/opportunities/tasks/{task_id}/&#x60;  Alternate route: &#x60;/legacy/opportunities/tasks/{task_id}/&#x60;  Alternate route: &#x60;/dev/opportunities/tasks/{task_id}/&#x60;   ---  This route is cached for up to 3600 seconds
     * @param {Number} taskId ID of an opportunities task
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.datasource The server name you would like data from (default to tranquility)
     * @param {String} opts.userAgent Client identifier, takes precedence over headers
     * @param {String} opts.xUserAgent Client identifier, takes precedence over User-Agent
     * @param {module:api/OpportunitiesApi~getOpportunitiesTasksTaskIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetOpportunitiesTasksTaskIdOk}
     */
    this.getOpportunitiesTasksTaskId = function(taskId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'taskId' is set
      if (taskId == undefined || taskId == null) {
        throw new Error("Missing the required parameter 'taskId' when calling getOpportunitiesTasksTaskId");
      }


      var pathParams = {
        'task_id': taskId
      };
      var queryParams = {
        'datasource': opts['datasource'],
        'user_agent': opts['userAgent']
      };
      var headerParams = {
        'X-User-Agent': opts['xUserAgent']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = GetOpportunitiesTasksTaskIdOk;

      return this.apiClient.callApi(
        '/opportunities/tasks/{task_id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
